# Site settings
title: CK Blog
name: CK Blog
url: "https://ckwang.win"
email: crazy2010king@gmail.com
description: CK Blog
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: CK  # Twitter ID
github_username:  crazy2005king@163.com # Github ID
weibo_username: CK  # Weibo ID
facebook_username: CK  # Facebook ID
duoshuo_username: crazy2005king # Duoshuo ID
baidushare_id: 898605931111111111 #  百度分享 ID
baidutongji_id: crazy2006king # 百度统计 ID
google-analytics_id: UA-89296169-1  # Google Analytics ID
rss_url: "/feed.xml"  # RSS 订阅 URL
logo_image: "/images/logo.png"  # LOGO 图片地址
# Build settings
gems: [jekyll-paginate]
markdown: rdiscount
highlighter: pygments
permalink: /:title/
paginate: 8
paginate_path: page/:num
 